### ISSUE TITLE
Errors in plain text processing

### ISSUE THREAD

**Issue by cneud** [KBNLresearch/europeananp-ner#21]
Processing a plain text input file (using either html or bio as output format) fails with the following stacktrace:

``java -Xmx800m -jar NerAnnotator-0.0.2-SNAPSHOT-jar-with-dependencies.jar -c text -f html -l fr -m fr=eunews.fr.crf.gz -n 1 test.txt
Container format: text
Loading language model for Französisch
fr -> eunews.fr.crf.gz
Done loading classifier
test.txt
Processing TEXT-File test.txt
Trying to process ALTO file file:/c:/ENP/test/test.txt
java.lang.NullPointerException
        at nl.kbresearch.europeana_newspapers.NerAnnotator.output.HtmlResultHandler.addToken(HtmlResultHandler.java:78)
        at nl.kbresearch.europeana_newspapers.NerAnnotator.alto.TxtProcessor.handlePotentialTextFile(TxtProcessor.java:83)
        at nl.kbresearch.europeana_newspapers.NerAnnotator.container.TextProcessor.processFile(TextProcessor.java:37)
        at nl.kbresearch.europeana_newspapers.NerAnnotator.container.ContainerHandleThread.call(ContainerHandleThread.java:40)
        at nl.kbresearch.europeana_newspapers.NerAnnotator.container.ContainerHandleThread.call(ContainerHandleThread.java:15)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Total processing time: 8718
0 container documents successfully processed, 1 with errors.
There were errors while processing.
``

**Comment by WillemJan** [comment]
This project is no longer maintained, pull request's welcome.

**Comment by cneud** [comment]
Ouch. In that case, we may have to move the repo to https://github.com/EuropeanaNewspapers/. Community maintenance will happen there, but since it is just a fork atm, GitHub provides no way to raise issues there.

**Comment by cneud** [comment]
The same goes for https://github.com/KBNLresearch/europeananp-dbpedia-disambiguation, I assume?

**Comment by WillemJan** [comment]
Discussion continued via mail.
